//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add error.
        /// </summary>
        internal static string AddError {
            get {
                return ResourceManager.GetString("AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        internal static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successful.
        /// </summary>
        internal static string AddSuccessful {
            get {
                return ResourceManager.GetString("AddSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        internal static string ButtonBackToList {
            get {
                return ResourceManager.GetString("ButtonBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code exists.
        /// </summary>
        internal static string CodeExists {
            get {
                return ResourceManager.GetString("CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to approve this data?.
        /// </summary>
        internal static string ConfirmApprove {
            get {
                return ResourceManager.GetString("ConfirmApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to block this data?.
        /// </summary>
        internal static string ConfirmBlock {
            get {
                return ResourceManager.GetString("ConfirmBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel requirement NCL this data?.
        /// </summary>
        internal static string ConfirmCancelRequest {
            get {
                return ResourceManager.GetString("ConfirmCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create this data?.
        /// </summary>
        internal static string ConfirmCreate {
            get {
                return ResourceManager.GetString("ConfirmCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this data?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Confirm Password&apos; and &apos;Password&apos; do not match.
        /// </summary>
        internal static string ConfirmPasswordAndPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordAndPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to re-active this user?.
        /// </summary>
        internal static string ConfirmReActive {
            get {
                return ResourceManager.GetString("ConfirmReActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to request this data to NCL?.
        /// </summary>
        internal static string ConfirmRequestNCL {
            get {
                return ResourceManager.GetString("ConfirmRequestNCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this data?.
        /// </summary>
        internal static string ConfirmSave {
            get {
                return ResourceManager.GetString("ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to submit this data?.
        /// </summary>
        internal static string ConfirmSubmit {
            get {
                return ResourceManager.GetString("ConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to unblock this data?.
        /// </summary>
        internal static string ConfirmUnblock {
            get {
                return ResourceManager.GetString("ConfirmUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data invalid.
        /// </summary>
        internal static string DataInvalid {
            get {
                return ResourceManager.GetString("DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        internal static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email exists.
        /// </summary>
        internal static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        internal static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is too large, please choose another photo or resize before uploading.
        /// </summary>
        internal static string ErrorYourFileIsTooLarge {
            get {
                return ResourceManager.GetString("ErrorYourFileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax number is invalid.
        /// </summary>
        internal static string FaxNumberIsInvalid {
            get {
                return ResourceManager.GetString("FaxNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format invalid.
        /// </summary>
        internal static string FormatInvalid {
            get {
                return ResourceManager.GetString("FormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From Excel.
        /// </summary>
        internal static string ImportFromExcel {
            get {
                return ResourceManager.GetString("ImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        internal static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log viewer.
        /// </summary>
        internal static string Logviewer {
            get {
                return ResourceManager.GetString("Logviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Management.
        /// </summary>
        internal static string MenuManagement {
            get {
                return ResourceManager.GetString("MenuManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name exists.
        /// </summary>
        internal static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not match.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        internal static string PhoneNumberIsInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-active.
        /// </summary>
        internal static string ReActive {
            get {
                return ResourceManager.GetString("ReActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        internal static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Level.
        /// </summary>
        internal static string RoleLevel {
            get {
                return ResourceManager.GetString("RoleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        internal static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful.
        /// </summary>
        internal static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/No.
        /// </summary>
        internal static string SNo {
            get {
                return ResourceManager.GetString("SNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        internal static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is invalid..
        /// </summary>
        internal static string TheFieldIsInvalid {
            get {
                return ResourceManager.GetString("TheFieldIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field must have a minimum length of 6.
        /// </summary>
        internal static string TheFieldPasswordMustBeaMinimumLengthOf6 {
            get {
                return ResourceManager.GetString("TheFieldPasswordMustBeaMinimumLengthOf6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string TheFieldShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("TheFieldShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password does not match.
        /// </summary>
        internal static string TheOldPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("TheOldPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to re-active user.
        /// </summary>
        internal static string UnableToReactiveUser {
            get {
                return ResourceManager.GetString("UnableToReactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        internal static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email actived.
        /// </summary>
        internal static string UserEmailActive {
            get {
                return ResourceManager.GetString("UserEmailActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users deleted.
        /// </summary>
        internal static string UsersDeleted {
            get {
                return ResourceManager.GetString("UsersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated.
        /// </summary>
        internal static string YourProfileHasBeenUpdated {
            get {
                return ResourceManager.GetString("YourProfileHasBeenUpdated", resourceCulture);
            }
        }
    }
}
